config/routes.rb
Rails.application.routes.draw do

  resources :news
  get '/catalog' => 'static_pages#catalog'

  get '/about' => 'static_pages#about'

  get '/contacts' => 'static_pages#contacts'

  as :user do
    get "/admin" => "devise/sessions#new"
  end

  resources :carousels
  resources :products, param: :shoe_type
  devise_for :users

  root 'static_pages#home'

end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
    has_attached_file :carousel_image, styles: { default: "1280x400>" },
                  default_url: "/images/:style/missing.png"
    validates_attachment_content_type :carousel_image, content_type: /\Aimage\/.*\Z/
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to carousels_path, notice: 'Carousel was successfully created.' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to carousels_path, notice: 'Carousel was successfully updated.' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carousel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:name, :link, :carousel_image)
    end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.slim
.panel.panel-default.form
  .panel-body
    = form_for @carousel do |f|
      - if @carousel.errors.any?
        #error_explanation
          h2 = "#{pluralize(@carousel.errors.count, "error")} prohibited this carousel from being saved:"
          ul
            - @carousel.errors.full_messages.each do |message|
              li = message

      .field.form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .field.form-group
        = f.label :link
        = f.text_field :link, class: "form-control"
      .field.form-group
        = f.label :carousel_image
        = f.file_field :carousel_image
      .actions = f.submit

app/views/carousels/edit.html.slim
h1 
  center Изменить Carousel

== render 'form'

= link_to 'Show', @carousel
'|
= link_to 'Back', carousels_path

app/views/carousels/index.html.slim
.container
  h1 Carousel
  table class="table table-striped"
      thead
        tr
          th ID
          th Название
          th Ссылка
          th Изображение
          th

      tbody
        - @carousels.each do |carousel|
          tr
            td = carousel.id
            td = carousel.name
            td = link_to carousel.link, carousel.link
            td = link_to image_tag(carousel.carousel_image.url(:default), :size => "128x40"), carousel
            td
              div class="btn-group" role="group" aria-label="..."
                button type="button" class="btn btn-default"
                  = link_to '', edit_carousel_path(carousel), class: 'glyphicon glyphicon-pencil'
                button type="button" class="btn btn-default"
                  = link_to '', carousel, data: { confirm: 'Are you sure?' }, method: :delete, class: 'glyphicon glyphicon-trash'


br

.container
  = link_to 'Создать', new_carousel_path, class: 'btn btn-primary btn-lg pull-right'
  br
  br
  br
  = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-default pull-right'
  br
  br

app/views/carousels/new.html.slim
h1 
  center Создать Carousel

== render 'form'

= link_to 'Back', carousels_path

app/views/carousels/show.html.slim
p#notice = notice

p
  strong Name:
  = @carousel.name
p
  strong Link:
  = @carousel.link

= link_to 'Edit', edit_carousel_path(@carousel)
'|
= link_to 'Back', carousels_path