config/routes.rb
Rails.application.routes.draw do

  resources :news
  get '/catalog' => 'static_pages#catalog'

  get '/about' => 'static_pages#about'

  get '/contacts' => 'static_pages#contacts'

  as :user do
    get "/admin" => "devise/sessions#new"
  end

  resources :carousels
  resources :products, param: :shoe_type
  devise_for :users

  root 'static_pages#home'

end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :news_image, styles: {medium: "250x160>", news_front: "500x270>"},
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :news_image, content_type: /\Aimage\/.*\Z/
  self.per_page = 10
  searchable do
    string :news_type
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page])
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :body, :news_image, :page, :news_type)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.slim
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      h2 = "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      ul
        - @news.errors.full_messages.each do |message|
          li = message

  .field
    = f.label "Название"
    = f.text_field :title, class: "form-control"
    br
  .field
    = f.label "Тип:", class: "form-group"
    |  
    = f.select :news_type, options_for_select(['Новость', 'Покупателю', 'Акции'])
  .field
    = f.label "Текст новости"
    br
    = f.text_area :body, as: :wysihtml5, class: 'wysihtml5'
  .field
    = f.label "Изображение"
    = f.file_field :news_image, class: "form-control"
  br
  .actions = f.submit


javascript:
  $(document).ready(function(){
    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });
  })

app/views/news/edit.html.slim
.container-fluid
  h1 Редактировать новость

  .row
    .col-sm-12
      == render 'form'

  = link_to 'Show', @news
  '|
  = link_to 'Back', news_index_path

app/views/news/index.html.slim
.container
  h1 Список новостей
  table class="table table-striped"
      thead
        tr
          th заголовок
          th Тип
          th Новость
          th Изображение
          th

      tbody
        - @news.each do |news|
          tr
            td = link_to news.title, news
            td = news.news_type
            td = truncate(news.body, length: 20)
            td = news.news_image
            td
              div class="btn-group" role="group" aria-label="..."
                button type="button" class="btn btn-default"
                  = link_to '', news, class: 'glyphicon glyphicon-resize-full'
                button type="button" class="btn btn-default"
                  = link_to '', edit_news_path(news), class: 'glyphicon glyphicon-pencil'
                button type="button" class="btn btn-default"
                  = link_to '', news, data: { confirm: 'Are you sure?' }, method: :delete, class: 'glyphicon glyphicon-trash'


  br

.container
  .row
    = link_to 'Создать новость', new_news_path, class: 'btn btn-primary btn-lg pull-right'
    br
    br
    br
    = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-default pull-right'
    br
    br
  center
    = will_paginate @news, renderer: BootstrapPagination::Rails

app/views/news/new.html.slim
.container-fluid
  h1 Создать новость

  .row
    .col-sm-12
      == render 'form'
  .row
    = link_to 'Back', news_index_path

  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br

app/views/news/show.html.slim
.container-fluid
  p#notice = notice

  .row
    h1.gradient = @news.title
    hr
  .row
    .col-sm-6
      = image_tag(@news.news_image.url(:news_front))
    .col-sm-6
      .fr-view 
        = @news.body.html_safe
      hr
      - if user_signed_in?
        .btn-group.pull-right
          .button type="button" class="btn btn-xs btn-default"
            = link_to "Изменить", edit_news_path(@news)
          .button type="button" class="btn btn-xs btn-danger"
            = link_to "", @news, data: { confirm: 'Are you sure?' }, method: :delete, class: "glyphicon glyphicon-trash"
  .row
    br
    br
    br
    br
    br
    br
    br
    br
    br
    br