config/routes.rb
Rails.application.routes.draw do

  resources :news
  get '/catalog' => 'static_pages#catalog'

  get '/about' => 'static_pages#about'

  get '/contacts' => 'static_pages#contacts'

  as :user do
    get "/admin" => "devise/sessions#new"
  end

  resources :carousels
  resources :products, param: :shoe_type
  devise_for :users

  root 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Shoesterra</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
<div class="container admin-panel">
  <div class="row">
    <!-- Split button -->
    <div class="btn-group">
      <button type="button" class="btn btn-xs btn-primary"><%= link_to "Изменить каталог", products_path %></button>
      <button type="button" class="btn btn-xs btn-primary">
        <%= link_to "", new_product_path, class: "glyphicon glyphicon-plus" %>
      </button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-xs btn-warning"><%= link_to "Изменить Carousel", carousels_path %></button>
      <button type="button" class="btn btn-xs btn-warning">
        <%= link_to "", new_carousel_path, class: "glyphicon glyphicon-plus" %>
      </button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-xs btn-info"><%= link_to "Изменить Новости", news_index_path %></button>
      <button type="button" class="btn btn-xs btn-info">
        <%= link_to "", new_news_path, class: "glyphicon glyphicon-plus" %>
      </button>
    </div>

    <div class="pull-right">
      Вы вошли как: <%= current_user.email %>
      <button type="button" class="btn btn-xs btn-danger">
        <%= link_to "", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %>
      </button>
      &nbsp;                                                                                     
    </div>
  </div>
</div>

<% end %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', alt: "ShoesTerra"), root_path, class: "navbar-brand img-responsive" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" id="nav">
        <%= content_tag :li, class: current_class?(root_path) do %>
          <%= link_to "Главная", root_path %>
        <% end %>
        <%= content_tag :li, class: current_class?(catalog_path) do %>
          <%= active_link_to "Каталог", catalog_path %>
          <ul class="hidden-xs">
            <li><%= link_to "Женская обувь", catalog_path(:sex => "Женская обувь") %></li>
            <li><%= link_to "Мужская обувь", catalog_path(:sex => "Мужская обувь") %></li>
          </ul>
        <% end %>
        <%= content_tag :li, class: current_class?(about_path) do %>
          <%= link_to "Новости", about_path %>
          <ul class="hidden-xs">
            <li><%= link_to "Покупателю", about_path(:news_type => "Покупателю") %></li>
            <li><%= link_to "Акции", about_path(:news_type => "Акции")%></li>
          </ul>
        <% end %>
        <%= content_tag :li, class: current_class?(contacts_path) do %>
          <%= link_to "Контакты", contacts_path %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

<footer class="footer">
  <div class="container-fluid">
    <div class="col-md-3 footer-column"><br><br><center><%= link_to image_tag("ST_logo.png", class: "img-responsive", style: "width:50%"), root_path %></center></div>
    <div class="col-md-3 footer-column">
      <h3>Меню</h3>
      <ul>
        <li><%= link_to "Главная", root_path %></li>
        <li><%= link_to "Каталог", catalog_path %></li>
        <li><%= link_to "Новости", about_path %></li>
        <li><%= link_to "Контакты", contacts_path %></li>
      </ul>
    </div>
    <div class="col-md-3 footer-column">
      <h3>Телефоны</h3>
      <ul>
        <li><a href="tel:+375296131973">+375 (29) 613 19 73</a></li>
        <li><a href="tel:+375291488488">+375 (29) 148 84 88</a></li>
      </ul>
    </div>
    <div class="col-md-3 footer-column">
      <h3>Контакты</h3>
      <ul>
        <li>Ул. Кульман 5б, ТЦ Атлантик, пав. 197</li>
        <li>E-mail: <a href="mailto:yora_horoshun@mail.ru">yora_horoshun@mail.ru</a></li>
        <br>
        <li>
          <%= link_to "", "https://www.facebook.com/profile.php?id=100013748957096", class: "icon-facebook-rect" %>
          <%= link_to "", "https://vk.com/id389907330", class: "icon-vkontakte-rect" %>
          <%= link_to "", "https://ok.ru/profile/570154850393", class: "icon-odnoklassniki-rect" %>
          <%= link_to "", "https://www.instagram.com/shoes_terra/", class: "icon-instagram-filled" %>
        </li>
      </ul>
    </div>
    </div> 
  </div>
</footer>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>